spring:
  mvc:
    format:
      date: iso
      date-time: iso
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s285582
    password: kaTpGQdiuT661RLN
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

server:
  port:
    8443